# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_check <- function(mat) {
    .Call(`_optimalDoe_d_check`, mat)
}

findMinDscore <- function(matrices, order) {
    .Call(`_optimalDoe_findMinDscore`, matrices, order)
}

coordinate_exchange <- function(N, K, order) {
    .Call(`_optimalDoe_coordinate_exchange`, N, K, order)
}

