# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_check <- function(mat) {
    .Call(`_optimalDoe_d_check`, mat)
}

findMinDscore <- function(matrices, order) {
    .Call(`_optimalDoe_findMinDscore`, matrices, order)
}

findMinAscore <- function(matrices, order) {
    .Call(`_optimalDoe_findMinAscore`, matrices, order)
}

coordinate_D <- function(N, K, model_order) {
    .Call(`_optimalDoe_coordinate_D`, N, K, model_order)
}

coordinate_A <- function(N, K, model_order) {
    .Call(`_optimalDoe_coordinate_A`, N, K, model_order)
}

